---
layout: post
status: publish
published: true
title: The Cost of Except in Python
author:
  display_name: dan.lecocq
  login: dan.lecocq
  email: dan.lecocq@kaust.edu.sa
  url: http://dan.lecocq.us/wordpress
author_login: dan.lecocq
author_email: dan.lecocq@kaust.edu.sa
author_url: http://dan.lecocq.us/wordpress
wordpress_id: 1052
wordpress_url: http://dan.lecocq.us/wordpress/?p=1052
date: '2012-01-08 12:19:03 -0800'
date_gmt: '2012-01-08 19:19:03 -0800'
categories:
- miscellany
tags: []
comments: []
---
<p>I was curious recently about how much of a performance penalty try&#47;except blocks incur in python. Specifically, 1) does it incur much of a cost if no exception is thrown (accepting only a penalty when something exceptional happens) and 2) how does it compare to if&#47;else statements where possible? A snippet to answer the first question:</p>
<pre lang='python'>
import timeit</p>
<p>withTryNoThrow = '''<br />
	try:<br />
		a = int('5')<br />
	except ValueError:<br />
		pass<br />
'''</p>
<p>withTryThrow = '''<br />
	try:<br />
		a = int('z')<br />
	except ValueError:<br />
		pass<br />
'''</p>
<p>withoutTry = '''<br />
	a = int('5')<br />
'''</p>
<p>results = {<br />
	'withoutTry'    : timeit.Timer(withoutTry    ).timeit(100000),<br />
	'withTryNoThrow': timeit.Timer(withTryNoThrow).timeit(100000),<br />
	'withTryThrow'  : timeit.Timer(withTryThrow  ).timeit(100000)<br />
}</p>
<p>for k, v in results.items():<br />
	print '%20s => %fs' % (k, v)<br />
<&#47;pre></p>
<p>For me, the results looked something like this:</p>
<pre>
      withTryNoThrow => 0.082781s<br />
          withoutTry => 0.082880s<br />
        withTryThrow => 0.261147s<br />
<&#47;pre></p>
<p>It would appear that while catching exceptions is expensive, catching non-exceptions is very cheap. I imagine that the reason is mostly because when you throw an exception, you actually instantiate an exception object of some kind, which necessarily introduces some overhead. In the absence of that object creation, things can be relatively fast.</p>
<p>Now, for the second question. This particular question came up when deciding whether or not I should try fetching a key from a dictionary and catching an exception when it's absent, or if I should use the get method and then check if the result is None.</p>
<pre lang='python'>
import timeit</p>
<p>setup = '''d = dict({<br />
	'some'   : 1,<br />
	'keys'   : 2,<br />
	'are'    : 3,<br />
	'present': 4,<br />
	'others' : 5,<br />
	'arent'  : 6<br />
})'''</p>
<p>tryExcept = '''<br />
	try:<br />
		a = d['doesntexist']<br />
	except KeyError:<br />
		pass<br />
'''</p>
<p>getIfElse = '''<br />
	a = d.get('doesntexist', None)<br />
	if a == None:<br />
		pass<br />
	else:<br />
		pass<br />
'''</p>
<p>getNoIf = '''<br />
	a = d.get('doesntexist', None)<br />
'''</p>
<p>results = {<br />
	'tryExcept' : timeit.Timer(tryExcept, setup).timeit(100000),<br />
	'getIfElse' : timeit.Timer(getIfElse, setup).timeit(100000),<br />
	'getNoIf'   : timeit.Timer(getNoIf  , setup).timeit(100000)<br />
}</p>
<p>for k, v in results.items():<br />
	print '%20s => %fs' % (k, v)<br />
<&#47;pre></p>
<p>For this second test, the results looked something like this for me:</p>
<pre>
             getNoIf => 0.019980s<br />
           tryExcept => 0.083638s<br />
           getIfElse => 0.027422s<br />
<&#47;pre></p>
<p>Obviously, if your program is amenable to just using a default value, then happiness ensues. Failing that, using the get method and then if&#47;else is much faster than the try&#47;except alternative.</p>
<p><em>Fine Print<&#47;em>: I am running Python 2.7.1 on a 2011-ish MacBookPro.</p>
